name: RetroArch Build

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        default: 'Release'
      tags:
        description: 'Tags' 
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login
    
jobs:
  download_game:
    name: Download nightly from buildbot
    runs-on: ubuntu-latest
    
    steps:
    - name: windows x64
      run: wget -P ~/windows/http://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z
    - name: Zip it up!    
      run: |
          cd ~/windows/
          7z e RetroArch.7z -y
          7z a retroarch-windows.zip * -y
          7z t retroarch-windows.zip -y
    - uses: josephbmanley/butler-publish-itchio-action@master
      name: deploy to itch.io
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-windows.zip
    - name: windows x86
      run: wget -P ~/windowsx86/ http://buildbot.libretro.com/nightly/windows/x86/RetroArch.7z
    - name: Zip it up!    
      run: |
          cd ~/windowsx86/
          7z e RetroArch.7z -y
          7z a retroarch-windows-x86.zip * -y
          7z t retroarch-windows-x86.zip -y
    - uses: josephbmanley/butler-publish-itchio-action@master
      name: deploy to itch.io
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: windowsx86
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-windows-x86.zip
    - name: linux x64
      run: wget ~/linux/ http://buildbot.libretro.com/nightly/linux/x86_64/RetroArch.7z
    - name: Zip it up!    
      run: |
          cd ~/linux/
          7z e RetroArch.7z -y
          7z a retroarch-linux.zip * -y
          7z t retroarch-linux.zip -y
    - uses: josephbmanley/butler-publish-itchio-action@master
      name: deploy to itch.io
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: linux
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-linux.zip


