name: RetroArch Build

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        default: 'Release'
      tags:
        description: 'Tags' 
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login
    
jobs:
  download_game:
    name: Download nightly from buildbot
    runs-on: ubuntu-latest
    
    steps:
    - name: windows x64
      run: wget http://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z
    - name: Zip it up!    
      run: |
          7z e RetroArch.7z -y
          7z a retroarch-windows.zip * -y
          7z t retroarch-windows.zip -y
    - uses: josephbmanley/butler-publish-itchio-action@master
      name: deploy to itch.io
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-windows.zip
    - name: windows x32
      run: |
          rm -rf * 
          wget http://buildbot.libretro.com/nightly/windows/x86/RetroArch.7z
    - name: Zip it up!    
      run: |
          7z e RetroArch.7z -y
          7z a retroarch-windows-x32.zip * -y
          7z t retroarch-windows-x32.zip -y
    - uses: josephbmanley/butler-publish-itchio-action@master
      name: deploy to itch.io
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: windowsx32
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-windows-x32.zip
    - name: linux x64
      run: |
          rm -rf *
          wget http://buildbot.libretro.com/nightly/linux/x86_64/RetroArch.7z
    - name: Zip it up!    
      run: |
          7z e RetroArch.7z -y
          7z a retroarch-linux-x86_64.zip * -y
          7z t retroarch-linux-x86_64.zip -y
    - uses: josephbmanley/butler-publish-itchio-action@master
      name: deploy to itch.io
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: linux-x86_64
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-linux-x86_64.zip
    - name: linux x64-qt
      run: |
          rm -rf *
          wget http://buildbot.libretro.com/nightly/linux/x86_64/RetroArch_Qt.7z
    - name: Zip it up!    
      run: |
          7z e RetroArch.7z -y
          7z a retroarch-linux-x86_64-qt.zip * -y
          7z t retroarch-linux-x86_64-qt.zip -y
    - uses: josephbmanley/butler-publish-itchio-action@master
      name: deploy to itch.io
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: linux-x86_64-qt
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-linux-x86_64-qt.zip
    - name: linux x86
      run: |
          rm -rf *
          wget http://buildbot.libretro.com/nightly/linux/x86/RetroArch.7z
    - name: Zip it up!    
      run: |
          7z e RetroArch.7z -y
          7z a retroarch-linux-x86.zip * -y
          7z t retroarch-linux-x86.zip -y
    - uses: josephbmanley/butler-publish-itchio-action@master
      name: deploy to itch.io
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: linux-x86
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-linux-x86.zip
    - name: linux x86-qt
      run: |
          rm -rf *
          wget http://buildbot.libretro.com/nightly/linux/x86/RetroArch_Qt.7z
    - name: Zip it up!    
      run: |
          7z e RetroArch.7z -y
          7z a retroarch-linux-x86-qt.zip * -y
          7z t retroarch-linux-x86-qt.zip -y
    - uses: josephbmanley/butler-publish-itchio-action@master
      name: deploy to itch.io
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: linux-x86-qt
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-linux-x86-qt.zip                              