name: RetroArch Build

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'version'     
        required: true
        default: '1.10.3'
    
jobs:
  download_game:
    name: Download nightly from buildbot
    runs-on: ubuntu-latest
    
    steps:
    - name: windows x64
      run: wget http://buildbot.libretro.com/stable/${{ github.event.inputs.version }}/windows/x86_64/RetroArch.7z
    - name: Zip it up!    
      run: |
          7z e RetroArch.7z -y
          rm -rf RetroArch.7z
          7z a retroarch-windows.zip * -y
    - uses: josephbmanley/butler-publish-itchio-action@master
      name: deploy to itch.io
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-windows-weekly.zip
          VERSION: ${{ github.event.inputs.logLevel }}                           
