# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Itchio-nightly:
    name: Download nightly from buildbot
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: fetch linux 
      run: |
        wget http://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z
    - name: |
          7z e RetroArch.7z
          7z a retroarch-windows.zip RetroArch\RetroArch-Win64\*
    - name: deploy to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-windows.zip
