name: RetroArch Build

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        required: true
        default: 'Release'
      tags:
        description: 'Tags' 
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login
    
jobs:
  Itchio-nightly:
    name: Download nightly from buildbot
    runs-on: ubuntu-latest
    
    steps:
    - name: fetch linux cores
      run: wget http://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z
    - name: Zip it up!    
      run: |
          7z e RetroArch.7z
          7z a retroarch-windows.zip RetroArch\RetroArch-Win64\*
    - uses: josephbmanley/butler-publish-itchio-action@master
      name: deploy to itch.io
      env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: RetroArchTest
          ITCH_USER: gadsby
          PACKAGE: retroarch-windows.zip
